import fs from "fs";
import path from "path";
import type { BuilderActionBatch, BuilderAction } from "../../agents/src/action-types";
import { assessAction } from "../../security/src/action-policy";
import { writeArtifact } from "./log-writer";

export interface DiffPreviewItem {
  index: number;
  actionType: BuilderAction["type"];
  target: string;
  exists: boolean;
  diff: string;
  risk: string;
  allowed: boolean;
  reason: string;
}

function simpleLineDiff(beforeText: string, afterText: string): string {
  const beforeLines = beforeText.split(/\r?\n/);
  const afterLines = afterText.split(/\r?\n/);
  const maxLen = Math.max(beforeLines.length, afterLines.length);
  const out: string[] = [];

  for (let i = 0; i < maxLen; i++) {
    const b = beforeLines[i];
    const a = afterLines[i];

    if (b === a) {
      if (typeof a !== "undefined") out.push(`  ${a}`);
      continue;
    }

    if (typeof b !== "undefined") out.push(`- ${b}`);
    if (typeof a !== "undefined") out.push(`+ ${a}`);
  }

  return out.join("\n");
}

function previewForAction(workspaceRoot: string, action: BuilderAction, index: number): DiffPreviewItem {
  const assessment = assessAction(action);

  if (action.type === "create_dir") {
    return {
      index,
      actionType: action.type,
      target: action.path,
      exists: fs.existsSync(path.join(workspaceRoot, action.path)),
      diff: `+ [directory] ${action.path}`,
      risk: assessment.risk,
      allowed: assessment.allowed,
      reason: assessment.reason,
    };
  }

  if (action.type === "run_command") {
    return {
      index,
      actionType: action.type,
      target: action.cwd ?? ".",
      exists: true,
      diff: `! command: ${action.command}`,
      risk: assessment.risk,
      allowed: assessment.allowed,
      reason: assessment.reason,
    };
  }

  const fullPath = path.join(workspaceRoot, action.path);
  const exists = fs.existsSync(fullPath);
  const beforeText = exists ? fs.readFileSync(fullPath, "utf-8") : "";

  let afterText = beforeText;
  if (action.type === "write_file") afterText = action.content;
  if (action.type === "append_file") afterText = beforeText + action.content;

  return {
    index,
    actionType: action.type,
    target: action.path,
    exists,
    diff: simpleLineDiff(beforeText, afterText),
    risk: assessment.risk,
    allowed: assessment.allowed,
    reason: assessment.reason,
  };
}

export function buildDiffPreview(workspaceRoot: string, batch: BuilderActionBatch) {
  const items = batch.actions.map((action, i) => previewForAction(workspaceRoot, action, i + 1));

  const lines: string[] = [];
  lines.push(`# ${batch.phase.toUpperCase()} Diff Preview`);
  lines.push("");
  lines.push(`**Run ID:** ${batch.runId}`);
  lines.push(`**Generated By:** ${batch.generatedBy}`);
  lines.push(`**Summary:** ${batch.summary}`);
  lines.push("");

  for (const item of items) {
    lines.push(`## ${item.index}. ${item.actionType} → ${item.target}`);
    lines.push("");
    lines.push(`- Exists: ${item.exists}`);
    lines.push(`- Allowed: ${item.allowed}`);
    lines.push(`- Risk: ${item.risk}`);
    lines.push(`- Reason: ${item.reason}`);
    lines.push("");
    lines.push("```diff");
    lines.push(item.diff || "(no textual diff available)");
    lines.push("```");
    lines.push("");
  }

  return {
    items,
    markdown: lines.join("\n"),
  };
}

export function writeDiffPreview(workspaceRoot: string, batch: BuilderActionBatch) {
  const preview = buildDiffPreview(workspaceRoot, batch);
  const artifactPath = writeArtifact(workspaceRoot, batch.runId, `${batch.phase}-diff-preview`, preview.markdown);
  return { ...preview, artifactPath };
}
