import type { BuilderActionBatch } from "../../agents/src/action-types";
import { assessAction } from "../../security/src/action-policy";
import { writeArtifact } from "./log-writer";

export function buildExecutionPreview(batch: BuilderActionBatch) {
  const assessments = batch.actions.map(assessAction);
  const riskSummary = {
    low: assessments.filter((a) => a.risk === "low").length,
    medium: assessments.filter((a) => a.risk === "medium").length,
    high: assessments.filter((a) => a.risk === "high").length,
  };

  const lines: string[] = [];
  lines.push(`# ${batch.phase.toUpperCase()} Execution Preview`);
  lines.push("");
  lines.push(`**Run ID:** ${batch.runId}`);
  lines.push(`**Generated By:** ${batch.generatedBy}`);
  lines.push(`**Summary:** ${batch.summary}`);
  lines.push("");
  lines.push("## Risk Summary");
  lines.push("");
  lines.push(`- Low: ${riskSummary.low}`);
  lines.push(`- Medium: ${riskSummary.medium}`);
  lines.push(`- High: ${riskSummary.high}`);
  lines.push("");
  lines.push("## Planned Actions");
  lines.push("");
  batch.actions.forEach((action, i) => {
    const a = assessments[i];
    lines.push(`### ${i + 1}. ${action.type}`);
    lines.push("");
    lines.push("```json");
    lines.push(JSON.stringify(action, null, 2));
    lines.push("```");
    lines.push(`- Allowed: ${a.allowed}`);
    lines.push(`- Risk: ${a.risk}`);
    lines.push(`- Requires Approval: ${a.requiresApproval}`);
    lines.push(`- Reason: ${a.reason}`);
    lines.push("");
  });

  return {
    markdown: lines.join("\n"),
    riskSummary,
    assessments,
  };
}

export function writeExecutionPreview(workspaceRoot: string, batch: BuilderActionBatch) {
  const preview = buildExecutionPreview(batch);
  const artifactPath = writeArtifact(workspaceRoot, batch.runId, `${batch.phase}-preview`, preview.markdown);
  return { ...preview, artifactPath };
}
