import fs from 'node:fs';
import path from 'node:path';
import { git, getLatestTag, getRootVersion } from './utils.js';

const targetVersion = process.argv[2] || getRootVersion();
const prevTag = process.argv[3] || getLatestTag();
const date = new Date().toISOString().split('T')[0];

const ROOT_DIR = path.resolve(import.meta.dirname, '../../');

interface ReleaseData {
  version: string;
  date: string;
  prevTag: string;
  commits: string[];
  categories: Record<string, string[]>;
}

function run() {
  console.log(`\n🔍 Generating Release Notes for v${targetVersion}...`);
  console.log(`   Comparing against: ${prevTag || 'initial commit'}`);

  const range = prevTag ? `${prevTag}..HEAD` : 'HEAD';
  let logs = '';
  try {
    logs = git(`log ${range} --oneline --no-merges`);
  } catch (e) {
    console.warn('⚠️ Could not fetch git logs. Falling back to empty history.');
  }

  const data: ReleaseData = {
    version: targetVersion,
    date,
    prevTag,
    commits: logs ? logs.split('\n') : [],
    categories: {
      '🚀 Added': [],
      '🛠️ Changed': [],
      '🐞 Fixed': [],
      '🔐 Security': [],
      '📝 Documentation': [],
      '📦 Misc': [],
    },
  };

  // 1. Categorize Commits
  for (const log of data.commits) {
    const msg = log.substring(log.indexOf(' ') + 1).trim();
    const lower = msg.toLowerCase();

    if (lower.startsWith('feat') || lower.startsWith('add')) data.categories['🚀 Added'].push(msg);
    else if (lower.startsWith('fix') || lower.startsWith('patch')) data.categories['🐞 Fixed'].push(msg);
    else if (lower.startsWith('sec') || lower.startsWith('auth')) data.categories['🔐 Security'].push(msg);
    else if (lower.startsWith('docs')) data.categories['📝 Documentation'].push(msg);
    else if (lower.startsWith('refactor') || lower.startsWith('perf') || lower.startsWith('chore')) data.categories['🛠️ Changed'].push(msg);
    else data.categories['📦 Misc'].push(msg);
  }

  // 2. Build Markdown
  let markdown = `# Release Notes — Code Kit Ultra v${data.version}\n\n`;
  markdown += `**Release Date:** ${data.date}\n`;
  markdown += `**Previous Tag:** ${data.prevTag || 'None'}\n\n`;

  markdown += `## 📝 Summary\n`;
  markdown += `[Provide a high-level summary of the primary value of this release here]\n\n`;

  markdown += `## ✨ Key Changes\n\n`;

  let totalChanges = 0;
  for (const [category, items] of Object.entries(data.categories)) {
    if (items.length > 0) {
      markdown += `### ${category}\n`;
      items.forEach(item => {
        markdown += `- ${item}\n`;
      });
      markdown += `\n`;
      totalChanges += items.length;
    }
  }

  if (totalChanges === 0) {
    markdown += `_No changes detected in git history for this range._\n\n`;
  }

  markdown += `## ✅ Verification Highlights\n`;
  markdown += `- [ ] Full typecheck and verification pass completed.\n`;
  markdown += `- [ ] All smoke and integration tests for core orchestrator passing.\n`;
  markdown += `- [ ] VS Code Extension verified against target IDE version.\n\n`;

  markdown += `## ⚠️ Risks & Notes\n`;
  markdown += `- [ ] No breaking architectural changes detected.\n`;
  markdown += `- [ ] Deprecation status: Legacy API keys are still supported but nudged toward sessions.\n\n`;

  markdown += `---\n*Generated by Code Kit Ultra Release Utility*\n`;

  // 3. Write and Output
  const fileName = `RELEASE_NOTES_v${data.version}.md`;
  const filePath = path.join(ROOT_DIR, fileName);
  fs.writeFileSync(filePath, markdown);

  console.log(`✅ Success! Release notes written to: ${fileName}`);
  console.log('\n--- PREVIEW ---\n');
  console.log(markdown);
  console.log('--- END PREVIEW ---\n');
}

run();
