import fs from "fs";
import path from "path";
import { execSync } from "child_process";
import type { BuilderAction, BuilderActionBatch } from "../../agents/src/action-types";
import type { CKMode } from "../../core/src/types";
import { MODE_EXECUTION_POLICIES } from "../../core/src/mode-controller";
import { assessAction, type ActionAssessment } from "../../security/src/action-policy";
import { writeActionLog, writeArtifact } from "./log-writer";
import type { RollbackMetadata } from "./rollback-metadata";

export interface ActionExecutionResult {
  action: BuilderAction;
  status: "executed" | "skipped" | "blocked" | "approval_required" | "dry_run";
  detail: string;
}

export interface ActionRunnerResult {
  runId: string;
  mode: CKMode;
  dryRun: boolean;
  summary: string;
  assessments: ActionAssessment[];
  results: ActionExecutionResult[];
  artifactPath?: string;
  logPath?: string;
  rollbackPath?: string;
}

function ensureParent(filePath: string) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
}

function executeFilesystemAction(workspaceRoot: string, action: BuilderAction): ActionExecutionResult {
  if (action.type === "create_dir") {
    fs.mkdirSync(path.join(workspaceRoot, action.path), { recursive: true });
    return { action, status: "executed", detail: `Directory created: ${action.path}` };
  }

  if (action.type === "write_file") {
    const fullPath = path.join(workspaceRoot, action.path);
    ensureParent(fullPath);
    fs.writeFileSync(fullPath, action.content, "utf-8");
    return { action, status: "executed", detail: `File written: ${action.path}` };
  }

  if (action.type === "append_file") {
    const fullPath = path.join(workspaceRoot, action.path);
    ensureParent(fullPath);
    fs.appendFileSync(fullPath, action.content, "utf-8");
    return { action, status: "executed", detail: `File appended: ${action.path}` };
  }

  return { action, status: "blocked", detail: "Unsupported filesystem action" };
}

function executeCommandAction(workspaceRoot: string, action: Extract<BuilderAction, { type: "run_command" }>): ActionExecutionResult {
  const cwd = path.join(workspaceRoot, action.cwd ?? ".");
  execSync(action.command, { cwd, stdio: "pipe" });
  return { action, status: "executed", detail: `Command executed: ${action.command}` };
}

function renderArtifact(batch: BuilderActionBatch, assessments: ActionAssessment[], results: ActionExecutionResult[]): string {
  const lines: string[] = [];
  lines.push(`# ${batch.phase.toUpperCase()} Action Batch`);
  lines.push("");
  lines.push(`**Run ID:** ${batch.runId}`);
  lines.push(`**Generated By:** ${batch.generatedBy}`);
  lines.push(`**Summary:** ${batch.summary}`);
  lines.push("");
  lines.push("## Actions");
  lines.push("");
  batch.actions.forEach((action, i) => {
    lines.push(`### ${i + 1}. ${action.type}`);
    lines.push("");
    lines.push("```json");
    lines.push(JSON.stringify(action, null, 2));
    lines.push("```");
    lines.push("");
  });
  lines.push("## Assessments");
  lines.push("");
  assessments.forEach((a) => {
    lines.push(`- **${a.action.type}** → allowed=${a.allowed}, risk=${a.risk}, approval=${a.requiresApproval} — ${a.reason}`);
  });
  lines.push("");
  lines.push("## Results");
  lines.push("");
  results.forEach((r) => {
    lines.push(`- **${r.action.type}** → ${r.status} — ${r.detail}`);
  });
  lines.push("");
  if (batch.recommendations?.length) {
    lines.push("## Recommendations");
    lines.push("");
    batch.recommendations.forEach((r) => lines.push(`- ${r}`));
  }
  lines.push("");
  return lines.join("\n");
}

export function runActionBatch(params: {
  workspaceRoot: string;
  mode: CKMode;
  batch: BuilderActionBatch;
  approvedGates?: string[];
  dryRun?: boolean;
}): ActionRunnerResult {
  const { workspaceRoot, mode, batch } = params;
  const approvedGates = params.approvedGates ?? [];
  const modePolicy = MODE_EXECUTION_POLICIES[mode];
  const dryRun = params.dryRun ?? modePolicy.dryRunByDefault;

  const assessments = batch.actions.map(assessAction);
  const results: ActionExecutionResult[] = [];
  const rollback: RollbackMetadata = { runId: batch.runId, entries: [] };

  for (const assessment of assessments) {
    const action = assessment.action;

    if (!assessment.allowed) {
      results.push({
        action,
        status: "blocked",
        detail: assessment.reason,
      });
      continue;
    }

    const gateApproved = approvedGates.includes(batch.phase);

    if (
      assessment.risk === "high" &&
      modePolicy.requireApprovalForHighRisk &&
      !gateApproved
    ) {
      results.push({
        action,
        status: "approval_required",
        detail: "High-risk action requires approval for this phase.",
      });
      continue;
    }

    if (
      assessment.risk === "medium" &&
      modePolicy.requireApprovalForMediumRisk &&
      !gateApproved
    ) {
      results.push({
        action,
        status: "approval_required",
        detail: "Medium-risk action requires approval for this phase.",
      });
      continue;
    }

    if (dryRun) {
      results.push({
        action,
        status: "dry_run",
        detail: "Dry run enabled. Action was not executed.",
      });
      continue;
    }

    try {
      if (action.type === "create_dir" || action.type === "write_file" || action.type === "append_file") {
        const result = executeFilesystemAction(workspaceRoot, action);
        results.push(result);

        rollback.entries.push({
          type: action.type === "create_dir" ? "dir_create" : action.type === "append_file" ? "file_append" : "file_write",
          target: "path" in action ? action.path : "",
          timestamp: new Date().toISOString(),
          note: action.reason ?? "No reason supplied",
        });
        continue;
      }

      if (action.type === "run_command") {
        if (!modePolicy.allowCommandExecution) {
          results.push({
            action,
            status: "blocked",
            detail: "Command execution is disabled in this mode.",
          });
          continue;
        }

        const result = executeCommandAction(workspaceRoot, action);
        results.push(result);

        rollback.entries.push({
          type: "command",
          target: action.command,
          timestamp: new Date().toISOString(),
          note: action.reason ?? "No reason supplied",
        });
      }
    } catch (error) {
      results.push({
        action,
        status: "blocked",
        detail: error instanceof Error ? error.message : "Unknown execution error",
      });
    }
  }

  const artifactMarkdown = renderArtifact(batch, assessments, results);
  const artifactPath = writeArtifact(workspaceRoot, batch.runId, `${batch.phase}-actions`, artifactMarkdown);
  const logPath = writeActionLog(
    workspaceRoot,
    batch.runId,
    `${batch.phase}-actions.log`,
    JSON.stringify({ batch, assessments, results }, null, 2),
  );
  const rollbackPath = writeActionLog(
    workspaceRoot,
    batch.runId,
    `${batch.phase}-rollback.json`,
    JSON.stringify(rollback, null, 2),
  );

  const summary = results.some((r) => r.status === "blocked")
    ? "Action batch completed with blocked actions."
    : results.some((r) => r.status === "approval_required")
    ? "Action batch requires approval before full execution."
    : dryRun
    ? "Action batch simulated in dry-run mode."
    : "Action batch executed successfully.";

  return {
    runId: batch.runId,
    mode,
    dryRun,
    summary,
    assessments,
    results,
    artifactPath,
    logPath,
    rollbackPath,
  };
}
